import { defineConfig } from 'vitest/config'
import react from '@vitejs/plugin-react'
import path from 'path'

export default defineConfig({
  plugins: [react()],
  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: './app/test/setup.ts',
    coverage: {
      provider: 'v8',
      reporter: ['text', 'html', 'lcov'],
      reportsDirectory: './coverage',
      exclude: [
        'node_modules/',
        '**/components/ui/Map.tsx',
        '.gitignore',
        '.next/',
        '.husky/',
        '.github/workflows/ci.yml',
        '.open-next/',
        'out/',
        'dist/',
        'build/',
        '.vinxi/',
        '.vinext/',
        '.agents/',
        '.git/',
        '.vscode/',
        '.idea/',
        '*.md',
        '*.json',
        'package-lock.json',
        'package.json',
        'skills-lock.json',
        '.wrangler/',
        'prisma/',
        'prisma/migrations/**',
        'prisma/seed.ts',
        '**/*.config.*',
        '**/*.config.js',
        '**/*.config.mjs',
        'postcss.config.mjs',
        'prisma.config.ts',
        '**/*.d.ts',
        '**/types/**',
        'next-env.d.ts',
        'worker-configuration.d.ts',
        '**/layout.tsx',
        '**/loading.tsx',
        '**/not-found.tsx',
        '**/error.tsx',
        '**/page.tsx',
        '**/template.tsx',
        '**/default.tsx',
        'middleware.ts',
        'proxy.ts',
        '.env',
        '.env.*',
        '.dev.vars',
        '.dev.vars.*',
        '**/*.test.ts',
        '**/*.test.tsx',
        '**/*.spec.ts',
        '**/*.spec.tsx',
        '**/mocks/**',
        'e2e/',
        'setup.ts',
      ],
      thresholds: {
        lines: 100,
        functions: 100,
        branches: 100,
        statements: 100,
      },
    },
  },

  resolve: {
    alias: {
      '@': path.resolve(__dirname, './'),
      'next/navigation': path.resolve(__dirname, './app/test/mocks/next-navigation.ts'),
      // Mock local pour next/link afin d'éviter les erreurs d'analyse ESM/CJS sous Vite
      'next/link': path.resolve(__dirname, './app/test/mocks/next-link.tsx'),
    },
  },
})